# Example development dockerfile
#
# VERSION               0.0.1
FROM        ubuntu:16.04
MAINTAINER  Riccardo De Leo <riccardo.deleo@covianalytics.com>

WORKDIR     /
ARG localIp
ARG fileConf

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install apt-utils git apache2 \
    php7.0 php7.0-cli php7.0-common php7.0-curl php7.0-dev php7.0-gd \
    php7.0-json php7.0-ldap php7.0-mysql php7.0-opcache php7.0-pspell \
    php7.0-readline php7.0-recode php7.0-sqlite3 php7.0-tidy php7.0-xml \
    php7.0-xmlrpc php-all-dev php7.0-bcmath php7.0-bz php7.0-intl\
    php7.0-mbstring php7.0-mcrypt php7.0-zip php7.0-xsl libapache2-mod-php7.0 \
    php-xdebug

RUN echo "xdebug.idekey=PHPSTORM" >> /etc/php/7.0/mods-available/xdebug.ini \
    && echo "xdebug.default_enable=0" >> /etc/php/7.0/mods-available/xdebug.ini \
    && echo "xdebug.remote_enable=1" >> /etc/php/7.0/mods-available/xdebug.ini \
    && echo "xdebug.remote_autostart=0" >> /etc/php/7.0/mods-available/xdebug.ini \
    && echo "xdebug.remote_connect_back=0" >> /etc/php/7.0/mods-available/xdebug.ini \
    && echo "xdebug.remote_port=9000" >> /etc/php/7.0/mods-available/xdebug.ini \
    && echo "xdebug.profiler_enable=0" >> /etc/php/7.0/mods-available/xdebug.ini \
    && echo "xdebug.remote_host=$localIp" >> /etc/php/7.0/mods-available/xdebug.ini

COPY ./env/dev/web/docker-entrypoint.sh /usr/bin/docker-entrypoint
RUN chmod +x /usr/bin/docker-entrypoint
RUN usermod -u 1000 www-data

WORKDIR /var/www/html

COPY $fileConf /etc/apache2/sites-available/000-default.conf

# Configure localhost in Apache
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN a2enmod rewrite

# Define default command
CMD ["docker-entrypoint"]
